language: node_js

node_js:
- node

install:
  - npm install -g codecov
  - npm install -g serverless
  - yarn install

cache:
  directories:
    - node_modules

script:
  - yarn test:api-coverage && codecov