language: node_js

node_js:
- node

cache:
  directories:
    - node_modules

script:
  - npm install -g serverless
  - npm test
  - babel-node ./node_modules/.bin/isparta cover _mocha --report lcovonly -- -R spec && codecov