language: node_js

node_js:
- node
- 6.5.0

install:
  - npm install -g codecov
  - npm install -g serverless
  - yarn install

cache:
  directories:
    - node_modules

script:
  - yarn test:coverage && codecov