service:
  name: reactServerless

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-finch
  - serverless-plugin-optimize

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: ap-southeast-1
  apiKeys:
    - ${self:custom.stage}-serviceKey
  environment:
    STAGE: ${self:custom.stage}
    SITELINK: ${self:custom.app.siteLink.${self:custom.stage}}
    STRIPE_SECRET_KEY: ${opt:stripe-secret}

custom:
  defaultStage: dev
  stage: ${opt:stage, self:custom.defaultStage}
  profiles:
    dev: serverlessDevProfile
    prod: serverlessProdProfile
  serverless-offline:
    port: 3001
  client:
    bucketName: ${opt:bucketName, 'sher.rapidstax.com'}
    distributionFolder: ${opt:distributionFolder, 'client/site/build'}
  cognitoUserPoolName: ${self:custom.stage}-SherTuitionUserPool
  app:
    siteLink:
      dev: "https://sher.rapidstax.com"
      prod: "https://sher.rapidstax.com"

functions:
  servicePing:
    handler: src/app/handlers/services.ping
    description: Service online availability test
    events:
      - http:
          path: services/ping
          method: get
          private: true
          cors: true
  cognitoCustomMessage:
      handler: src/app/handlers/awsCognito.customMessage
      description: Cognito user signup custom message trigger lambda function
      events:
        - cognitoUserPool:
            pool: SherTuitionUserPool
            trigger: CustomMessage
  billingCreateCharge:
      handler: src/app/handlers/billing.createCharge
      description: Stripe create new charge
      events:
        - http:
            path: billing/charge
            method: post
            private: true
            cors: true

resources:
  Resources:
    CognitoUserPoolSherTuitionUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: ${self:custom.stage}-SherTuitionUserPool
        EmailConfiguration:
          ReplyToEmailAddress: "no-reply@shertuition.com"
        Schema:
          - AttributeDataType: String
            Mutable: True
            Name: email
            Required: True
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: False
            RequireSymbols: False
            RequireUppercase: False
    CognitoUserPoolClientSherTuitionUserPoolClientWebapp:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: SherTuitionUserPoolClientWebapp
        UserPoolId:
          Ref: CognitoUserPoolSherTuitionUserPool
        WriteAttributes:
          - email
          - family_name
          - given_name
          - phone_number