service:
  name: reactServerless

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-finch

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: ap-southeast-1
  apiKeys:
    - ${self:custom.stage}-serviceKey
  environment:
    stage: ${self:custom.stage}
    cognitoUserPoolId: ${self:custom.cognitoUserPoolName}

custom:
  defaultStage: dev
  stage: ${opt:stage, self:custom.defaultStage}
  profiles:
    dev: serverlessDevProfile
    prod: serverlessProdProfile
  serverless-offline:
    port: 3001
  client:
    bucketName: ${opt:bucketName, 'sher.rapidstax.com'}
    distributionFolder: ${opt:distributionFolder, 'client/site/build'}
  cognitoUserPoolName: ${self:custom.stage}-SherTuitionUserPool

functions:
  servicePing:
    handler: src/app/handlers/services.ping
    description: Service online availability test
    events:
      - http:
          path: services/ping
          method: get
          private: true
          cors: true
  cognitoCustomMessage:
      handler: src/app/handlers/awsCognito.customMessage
      description: Cognito user signup custom message trigger lambda function
      events:
        - cognitoUserPool:
            pool: SherTuitionUserPool
            trigger: CustomMessage

resources:
  Resources:
    CognitoUserPoolSherTuitionUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: ${self:custom.stage}-SherTuitionUserPool
        EmailConfiguration:
          ReplyToEmailAddress: "no-reply@shertuition.com"
        Schema:
          - AttributeDataType: String
            Mutable: True
            Name: email
            Required: True
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: False
            RequireSymbols: False
            RequireUppercase: False
    CognitoUserPoolClientSherTuitionUserPoolClientWebapp:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: SherTuitionUserPoolClientWebapp
        UserPoolId:
          Ref: CognitoUserPoolSherTuitionUserPool
        WriteAttributes:
          - email
          - family_name
          - given_name
          - phone_number